### ISSUE TITLE
Missing Model Status Table

### ISSUE THREAD

**Issue by miyurud** [miyurud/jasminegraph#127]
Even though in the Frontend the model status table is referred it has not been created. @DamithaSenevirathne Can you please check this and send a fix? [See](https://github.com/miyurud/jasminegraph/blob/fl/src/frontend/JasmineGraphFrontEnd.cpp#L289)

**Comment by tmkasun** [comment]
I encounter the same issue in the 
```
bool JasmineGraphFrontEnd::modelExists(string path, SQLiteDBInterface sqlite)
``` 
which expect to have `model_status_idmodel_status` column in the `model` DB
in here
![image](https://user-images.githubusercontent.com/3313885/120080634-8e219800-c0d7-11eb-9a78-f7fb25df595c.png)

But I think it's missing the the DB file `jasminegraph/metadb/jasminegraph_meta.db`

**Comment by miyurud** [comment]
@DamithaSenevirathne Still we do not have the model_status table in the metadb. Can you please check?
