### ISSUE TITLE
Build two binaries for server and worker

### ISSUE THREAD

**Issue by tmkasun** [miyurud/jasminegraph#60]
Use two targets in CMake and, generate two binaries for JasmineGraph server and worker profiles.

**Comment by miyurud** [comment]
When deploying JasmineGraph on multiple computers this might give some advantage in terms of binary size. For deploying on a single system (like a share memory server) there is no advantage of doing this. However, there will be added complexity of determining which goes to which binary. Furthermore, this will be effective to do so if there will be significantly different sized master (i.e., server as you mentioned) and worker binaries. This we will have to measure and evaluate.
